### ISSUE TITLE
G4 - Menu navigation function on Mobile device

### ISSUE THREAD

**Issue by Dmelady** [brharp/hjckrrh#101]
Currently icon that produces single, consolidated menu which is problematic and confusing on mobile device (listing site menu at very bottom); solution to add clarity for users for site menu versus UG menu

**Comment by Dmelady** [comment]
Miranda has taken notes on this.

**Comment by mmafe** [comment]
**Notes on Solution:** We'll be adding two buttons. Global nav will be in the red navigation area (using a hamburger icon). Local nav will be to the right of the site title (using a downward-facing chevron icon, so as to differentiate between the two buttons).

**Comment by jszasz** [comment]
Confirmed Fixed.
