### ISSUE TITLE
FT3 Theming - Featured Teaser lists - Summary spacing issue

### ISSUE THREAD

**Issue by Dmelady** [brharp/hjckrrh#103]
When  a summary is added, unnecessary extra padding is added below element. See screen capture - Wheat for Baking for example

**Comment by Dmelady** [comment]
![teaser space issue](https://cloud.githubusercontent.com/assets/13487599/8932875/c85c2758-350d-11e5-95d7-6818587fc3a3.jpg)

**Comment by mmafe** [comment]
The summary text includes an extra space at the end. Remove space to fix.

<div class="media-summary">
   <p>Featuring Jane Bock, adjunct professor and research associate.</p> 
   <p>&nbsp;</p>
</div>
