### ISSUE TITLE
P1 - Export default layouts for listing / detail pages for Page, Events, News, Services, FAQ

### ISSUE THREAD

**Issue by Dmelady** [brharp/hjckrrh#110]
Right side - default to include; Share This, Menus, and News Archives....and every other important widget (ie new archives)

Find Related Services by Keyword in Bottom section (Miranda to try small formatting)

**Comment by brharp** [comment]
Is this a request to update the default layouts? If you could confirm that the page layouts are correct on the aodademo site, then I can update the standard layouts to match.

**Comment by mmafe** [comment]
Updating aodademo to show layouts for all detail pages and listing pages. Will comment when complete.

**Comment by mmafe** [comment]
Updated detail page and listing page layouts on aodademo for events, news, page, services, faq, and features (listing).

Just as a heads up, I've gone with a 3-panel bootstrap layout just in case people wish to use all three in future (left panel - 0 columns, middle panel - 8 columns, and right panel - 3 columns + 1 offset).

**Comment by brharp** [comment]
Done
