### ISSUE TITLE
Files Directory on CCS - check permissions to ensure we can access

### ISSUE THREAD

**Issue by Dmelady** [brharp/hjckrrh#111]
So an anonymous user can access the file

**Comment by brharp** [comment]
The permissions look okay. Can you give me an example of a file that you can't access?

**Comment by mmafe** [comment]
**Source URL:** https://aoda.web.uoguelph.ca/ccs/service/organizational-web-hosting
**File:** https://aoda.web.uoguelph.ca/ccs/sites/uoguelph.ca.ccs/files/CCS%20Web%20Hosting%20Service%20Agreement.pdf

**Comment by brharp** [comment]
I have fixed the file permissions on the CCS web site.

 

M. Brent Harp

Analyst, Business Solutions
Computing and Communications Services (CCS)
University of Guelph

519-824-4120 Ext 56621
brharp@uoguelph.ca <mailto:brharp@uoguelph.ca> 

www.uoguelph.ca/ccs <http://www.uoguelph.ca/ccs>

**Comment by mmafe** [comment]
Thanks!
