### ISSUE TITLE
S1- Share this page is now broken- was working

### ISSUE THREAD

**Issue by anncesar** [brharp/hjckrrh#112]
Looks like url has duplicate site name see CCS website

**Comment by brharp** [comment]
When creating social media accounts with relative URLs, the base path (e.g. '/css') can be omitted from the path. For example, to create a social media account on the CCS site that links to <https://www.uoguelph.ca/ccs/about-ccs/subscriptions>, the correct path to use is 
<about-ccs/subscriptions>
