### ISSUE TITLE
FT0 - 'Create Feature' search box prevents typing in top field

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#12]
When in 'Add Content>Create Feature', if you click 'Search' and then scroll to the top of the page with the search box still open, you are unable to type anything in the 'Search for content' form.

**Comment by brharp** [comment]
Is this only a problem with the "Bootstrap" theme, or does it happen when editing content with the "backend" theme as well? I have switched content editors to use the "backend" theme, so if it's the former this may not be an issue.

**Comment by jpinsent** [comment]
Just tested it with the "backend" theme and it does not appear to be an issue, although there is a slight graphical bug. If the user scrolls up with the search box open, the main menu bar slightly obscures the search box, but it does not prevent the user from typing in it.

**Comment by jszasz** [comment]
The origional issue was with the bootstrap theme, and the graphical bug is also with the bootstrap theme. Everything works fine in the backend theme.
