### ISSUE TITLE
FT0 - 'Create Feature' search function ambiguous

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#13]
This refers to the 'Search' option in 'Add Content>Create Feature'.

Search button's location and text on the page makes its function somewhat ambiguous - could appear at the top of the page and read: "Search for content to be featured"

**Comment by brharp** [comment]
I changed the label of the button to "Search for content"

**Comment by jpinsent** [comment]
Thanks Brent. That fixes this issue.
