### ISSUE TITLE
N6 - Has no title

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#130]
needs "Browse News by Topic"

**Comment by mmafe** [comment]
Fixed as part of hotfix_20150807.3.0

**Comment by jpinsent** [comment]
'News Topics' heading 2 now appears above. This issue has been fixed.

![news category](https://cloud.githubusercontent.com/assets/12450480/9275078/a6ea89bc-4268-11e5-9eac-0a672c6df1c5.PNG)
