### ISSUE TITLE
N6 - Catagories should be listed instead of keywords

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#131]
Current this view is using keywords when it should be using categories.

**Comment by mmafe** [comment]
Fixed as part of hotfix_20150807.3.0

**Comment by jpinsent** [comment]
Confirmed fixed. Keywords have been moved to the side pane above News Archive and the category listing appears underneath.
Looks like this:
![news category](https://cloud.githubusercontent.com/assets/12450480/9274297/7f0122c2-4262-11e5-9698-d64b7eae6b7c.PNG)
