### ISSUE TITLE
E8b - Prev and Next buttons overlap, also overlap title

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#134]
![overlap 1](https://cloud.githubusercontent.com/assets/12450523/9201163/90a42042-4019-11e5-8086-d7a0b2e93c79.PNG)
![overlap 2](https://cloud.githubusercontent.com/assets/12450523/9201164/90ad6486-4019-11e5-88c9-a0b4471b1cf1.PNG)

Picture 1 is when it is, on narrow view. The buttons are overlapping themselves, and also overlapping the title.

Picture 2 is when its full screen. the buttons are still overlapping each other.

**Comment by mmafe** [comment]
Fixed as part of hotfix_20150807.3.0

**Comment by jpinsent** [comment]
New buttons are lookin' gooood. This issue has been resolved.

Standard:
![new buttons](https://cloud.githubusercontent.com/assets/12450480/9274209/a4c1ddea-4261-11e5-8a52-378120a86c07.PNG)
Responsive:
![new buttons responsive](https://cloud.githubusercontent.com/assets/12450480/9274222/cf7ee280-4261-11e5-964e-d20c8af4b406.PNG)
