### ISSUE TITLE
E3, N3 - More buttons are not showing

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#137]
More buttons are not showing

**Comment by mmafe** [comment]
Fixed in hotfix_20150807.3.0

**Comment by jpinsent** [comment]
Looks like both buttons are there now. Confirmed fixed.

![more news](https://cloud.githubusercontent.com/assets/12450480/9274358/2246cc84-4263-11e5-8659-d472d9d9e95b.PNG)

![more events](https://cloud.githubusercontent.com/assets/12450480/9274360/264e926c-4263-11e5-8d6d-6405cd2eebc5.PNG)
