### ISSUE TITLE
FT0 - 'Create Feature' search function doesn't search

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#14]
This refers to the 'Search' option in 'Add Content>Create Feature'.

Upon using the 'Search' option, it only fills out the 'Link' field with the searched content. The title and featured image associated with the searched page are not updated into their associated fields.

**Comment by brharp** [comment]
For this first iteration, the title and image will need to be entered separately.

**Comment by jszasz** [comment]
New issue with the search function. When you first click on "search for content" the "linkit" box pops up blank (this happens on both chrome and firefox). After closing the blank box and clicking on search for content again, the actual search box shows up fine.

When typing in the search box a the top, it never actually searches. I tried with the title of a page and the url of a page and neither search worked.

**Comment by Dmelady** [comment]
Please remove 'search for content' button from Feature Content type. It seems buggy.

**Comment by jpinsent** [comment]
It looks like the Search option has been removed from Feature. This is no longer an issue.
