### ISSUE TITLE
E8 - Month title should be August 2015 instead of Saturday, August 1, 2015

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#141]
Month title should be August 2015 instead of Saturday, August 1, 2015

**Comment by mmafe** [comment]
Fixed as part of hotfix_20150807.3.0

**Comment by jpinsent** [comment]
This has been fixed for Events by Month.

![e8 fix 2](https://cloud.githubusercontent.com/assets/12450480/9274408/90806296-4263-11e5-8cfc-e11fd1f18fd1.PNG)
