### ISSUE TITLE
BR1 - Slide pagination changes colour on hover

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#144]
Slide pagination needs to be disabled on hover. 
Occurred as a result of fixing validation errors on <div class="btn etc." disabled>
To fix, re-add disabled as a class.

**Comment by mmafe** [comment]
Fixed as part of hotfix_20150807.3.0

**Comment by jpinsent** [comment]
The 'Slide # of #' text no longer changes colour on hover. Confirmed fixed.
