### ISSUE TITLE
G11/N1 (Variation B) - News listing by keyword is not titled properly

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#145]
It doesn't seem like the news listing page for filtered by keyword is working. The title of the page is just "News" and there is no indication of which keyword you are searching by.

This is related to [N1 (Variation B)](https://trello.com/c/O1pg8Brz).

**Comment by mmafe** [comment]
Seems to be working on AODA Demo, CCS, etc. 

OAC has its News feature overridden, so I believe that's why we're still seeing News on there as opposed to News related to [keyword].
