### ISSUE TITLE
G6 - Distance Education links to broken URL

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#148]
**https**://www.coles.uoguelph.ca does not work.

Switch to www.opened.uoguelph.ca

**Comment by mmafe** [comment]
Fixed as part of hotfix_20150807.3.0

**Comment by jpinsent** [comment]
The link appears to have been changed to https://www.opened.uoguelph.ca/, which doesn't seem to be working unless you take out the 'https://'.

**Comment by mmafe** [comment]
Updated to http. Fixed as part of hotfix_20150807.3.0

**Comment by mmafe** [comment]
(Also fixed CSAHS and OAC links)

**Comment by jpinsent** [comment]
Tested & all links seem to be working.
