### ISSUE TITLE
G4 - Local menu theme / colour When selected

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#15]
![menu colour test](https://cloud.githubusercontent.com/assets/12450523/7654623/8cb148ec-faec-11e4-8782-cbbcc7a79019.png)

The colour of the local menu (oragnge) goes to a inverted grey colour when you are on the selected page. See attached picture.

**Comment by jpinsent** [comment]
Menu bar has been updated. This is no longer an issue.
