### ISSUE TITLE
E15 - Past Events occur in the wrong order (closest date to today should be at the top)

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#151]
Past events occur in the wrong order (closest date to today should be at the top).

Option A - leave as is and update spec
Option B - clone E1 and switch the order.

**Comment by jpinsent** [comment]
Looks like it's working as described above. Events closest to today are appearing at the top of the page and the oldest are appearing at the bottom.

Order I'm seeing is as follows, from the top of the page to the bottom:
Event from August 28th, 2015
Event from August 26th, 2015
Event from August 5th, 2015
Event from July 25th, 2015
...
Event from January 25th, 2012
