### ISSUE TITLE
G12 - Side menu pane collapsed menus aren't indicated by screen reader

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#155]
Side menu panes are not indicated as collapsed by screen readers. An arrow appears next to it for sighted users to indicate that the button is collapsed, but there is no indication for people using screen readers.

![screenreader issue](https://cloud.githubusercontent.com/assets/12450480/9282708/62c9b698-429c-11e5-9a8d-d13c4f46a52c.PNG)
NVDA reads this as:
"heading level 2
Resources for Students
list with 19 items
visited link
Resources for Students
visited link
Welcome
visited link
FAQs"

**Comment by mmafe** [comment]
Unless we're able to expand and collapse the menu item (without going to a new page), I think it would be confusing to announce that the menu item is collapsed.

These are essentially lists and nested lists, which does end up being communicated to assistive tech. I hear:

"Probation, visited link Probation Information
list with 2 items
Resources link Probation Information, Resources
Services link Probation Information, Services"

**Suggested Improvement:** As an alternative, what if we remove the arrow completely unless we're on an active parent that's open?

See https://aoda.web.uoguelph.ca/uaic/probation as an example. Right now, even though Probation is the open item, FAQs looks as though it's the parent of Academic Advising (which even I find confusing. :))

**Comment by mmafe** [comment]
**Description of Fix:** We'll remove the caret from any menu items that are not active. If an active menu item has nested children open, we'll have a caret.

**Comment by mmafe** [comment]
Applied as part of hotfix_20140807.4.0

**Comment by jpinsent** [comment]
The carat seems to be showing up as described and the fix seems to resolve this issue. 

Although it is still not picked up by the screen reader, as long as the menu is expanded the screen reader states that the next menu items are part of a list, allowing screen reader users to infer that the menu items are nested under the preceding link.
