### ISSUE TITLE
Platform ability to logout

### ISSUE THREAD

**Issue by Dmelady** [brharp/hjckrrh#158]
Maybe wrong but seems to have no ability to logout if logged in.
![image](https://cloud.githubusercontent.com/assets/13487599/9311468/57acf46a-44e4-11e5-96c4-b11692ae7b57.png)

**Comment by jszasz** [comment]
I know the 'login link' which is /user is hidden from all the sites as well, so that could be why logout is hidden too.

To logout, go to /user/logout on any site.
