### ISSUE TITLE
SR2 - Hide Service Audience field in Service Detail View

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#177]
Please hide the service audience field in the service detail view.

**Comment by mmafe** [comment]
**Note:** We hide the service audience field, but the keywords should still be available via the Find related Services by Keyword view. Created an issue to make sure we remember to add that: https://github.com/brharp/hjckrrh/issues/215

**Comment by jpinsent** [comment]
Service Audience used to show up on the detail page as "Who is eligible to use this service?". It isn't showing up on any of the service detail pages on AODA Demo anymore. Looks like this issue is resolved.
