### ISSUE TITLE
SR3/SR4 - Remove underlines from any lists (not surrounded by content) on services features

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#179]
Remove underlines from any lists (not surrounded by content) on services features

**Comment by mmafe** [comment]
**Note:** Affected views are:
- All Services (alphabetical listing)
- Services by Audience (list)

**Comment by jpinsent** [comment]
Looks like it's working on the AODA Demo site. Underlines no longer appear on items under All Services (A-Z) and Services by audience
