### ISSUE TITLE
E9a - (Events, This Week) - Different formatting for images

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#183]
Comparing the look of the events on the "upcoming Events" and "This Week" tabs, the images on the "This Week" tab have a boarder around them , where was the "Upcoming Events" does not.

Suggest making the boarder not show, so each event can use up more of the screen space, and both views look similar.
(this week) ![this week](https://cloud.githubusercontent.com/assets/12450523/9497720/5aa6f1be-4be4-11e5-9c93-0d818a02d365.PNG)
(upcoming events) ![upcoming events](https://cloud.githubusercontent.com/assets/12450523/9497722/5c471fc6-4be4-11e5-9e66-9eeceb4ba310.PNG)

**Comment by jpinsent** [comment]
The border no longer appears around images, thus resolving this issue. However, there is now a large empty gap between the image and the text on the page for 'This Week'.

This issue is technically resolved, so I will create a new normal priority issue to address this.
