### ISSUE TITLE
N0 - Category autofill colours

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#19]
![n0 - category colours](https://cloud.githubusercontent.com/assets/12450523/7655834/5d18411e-faf4-11e4-8276-9a329b5f0487.png)

See image. The colours of the autofill drop down for the "category" field is really bad. grey on dark blue.

**Comment by jpinsent** [comment]
This issue has been resolved. Category is now a dropdown menu and the autofill for keywords appears as black text on a white background now.
