### ISSUE TITLE
SR3 - Lowercase letters in Services A-Z

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#199]
I'm pretty sure this issue has been discovered before, but I didn't see it on the tracker. My apologies if this has already been reported. 

Some of the letters on the letter navigation for Services A-Z are lowercase while the rest are uppercase. 'g', 'j' and 't' are all lowercase.

![a to z](https://cloud.githubusercontent.com/assets/12450480/9660392/6edcde92-5223-11e5-827f-55ff5c8032cc.PNG)

Furthermore, lowercase letters appear in addition to uppercase letters on the actual list if the page title starts with a lowercase letter. Not sure if this is intended or not
![services a to z](https://cloud.githubusercontent.com/assets/12450480/9660537/196bc5a8-5224-11e5-8ec7-42dfdf47880d.PNG)

https://aoda.web.uoguelph.ca/aodademo/services/alphabetical

**Comment by jpinsent** [comment]
It seems like the letter navigation is just grabbing the first character that appears alphabetically. For instance, if the list for lowercase 'h' has one page called 'hello' and the list for uppercase 'H' has one page called 'Home', a lowercase 'h' will be used in the letter nav since it shows up first.

**Comment by mmafe** [comment]
We're also getting a duplicate letter in the listing below.

![duplicate-letters](https://cloud.githubusercontent.com/assets/1927902/9879879/363c778c-5b97-11e5-875c-0e5c112ce39e.png)

**Comment by jpinsent** [comment]
This issue appears to have been resolved. Service titles beginning with lowercase letters are now properly grouped with the uppercase titles. Only capital letters appear in the listing.

![fixed](https://cloud.githubusercontent.com/assets/12450480/9961390/4c188a24-5dee-11e5-85bc-1f16158524bf.PNG)

![fixed2](https://cloud.githubusercontent.com/assets/12450480/9961397/5036a33e-5dee-11e5-92b8-361200277b4b.PNG)
