### ISSUE TITLE
FT1 - Title overflows past view

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#2]
- Maximum length of Title attribute of a feature allows the title to exceed the border of the Featured Item and stretch the page (see FT1_LengthBug.png). Max length of title should be shorter or should at least be contained within the featured item border
![ft1_lengthbug](https://cloud.githubusercontent.com/assets/1927902/7639779/7c82d2c4-fa4c-11e4-8047-9d49ce2c3158.png)

**Comment by jszasz** [comment]
This is no longer an issue. It will only show a certain length of the long title (aaaaaaaaa), but it works fine now with hyphens. It is only an issue in the detail page, but that is never shown to the users. The error is also a user error not a feature error.
