### ISSUE TITLE
G3/G7 - Local search and Global search have the same page title

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#205]
The pages you get to after searching with the local and global search input have the same page title ("Search"). The global search tells you it will search the entire U of G site when you use the input box at the top of each page, but the page itself gives no indication of the range of the search. The local search gives no indication whatsoever (except for on the main page of some websites, where a heading is present).

Suggest changing the title of the local search page from "Search" to "Local search".

**Comment by mmafe** [comment]
Issue appears to be resolved. Currently the page <title> elements contain the following:
- Global search page title is "Search | University of Guelph"
- Local search page title is "Search | [name of site]"

These appear to be sufficiently different.

**Comment by mmafe** [comment]
@jpinsent When time permits, could you please update the accessibility report for the G3 local search: https://trello.com/c/4e3sjCQN/49-g3-local-search
