### ISSUE TITLE
G1 - Breadcrumbs missing from International Development Studies page on Grad Studies site

### ISSUE THREAD

**Issue by enichol** [brharp/hjckrrh#223]
https://www-stage.uoguelph.ca/graduatestudies/programs/idev

page's breadcrumbs do not follow path to current page, unlike similar pages for other grad programs

**Comment by jpinsent** [comment]
This seems to be an issue with the content. The breadcrumb trail is not being generated since this page is not currently placed within a menu. It should be placed under Prospective Students / Academic Programs / All Programs on the menu structure.
