### ISSUE TITLE
Add underline styling for links inside description list <dl>

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#234]
Add underline styling for links inside description list <dl>.

**Example:** https://www.uoguelph.ca/uaic/acronyms-c

**Comment by mmafe** [comment]
Update pushed to the develop branch (e.g. https://dev.web.uoguelph.ca/uaic/acronyms-c) for testing. If all looks good, we can push to the master branch.

**Note:** Also added the styling for links contained in blockquotes, figcaption, and pre elements.

**Comment by jpinsent** [comment]
The styled links appear to be underlined when contained in description lists, blockquotes, figcaptions and pre elements. This issue has been resolved.
