### ISSUE TITLE
P0 - Can't make a table in editor

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#24]
Im on https://aoda.web.uoguelph.ca/uaic/ as wbsadmin, and I only have access to Plain text and Basic HTML editor. The Basic HTML editor doesn't allow you to make a table, nor do I have access to the Full HTML editor.

On the https://aoda.web.uoguelph.ca/ccs/ site as wbsadmin, I do have access to Full HTML.

ALSO: The author doesn't haev access to Full HTML ever, so an author can not make a table on a basic Page.

**Comment by brharp** [comment]
The basic HTML editor (given to authors) can now insert tables.
