### ISSUE TITLE
SR1 - Focus on Service by Category links is almost invisible

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#241]
We decided that the focus indicator on the Services by Category links was not enough to pass the Focus Visible criterion on the WCAG 2.0. This needs to be fixed for CCS to pass this criterion.

Unfocused:
![unfocused](https://cloud.githubusercontent.com/assets/12450480/10288991/166df628-6b6a-11e5-80b5-786a509b16ba.PNG)
Focused:
![focused](https://cloud.githubusercontent.com/assets/12450480/10288993/19702db4-6b6a-11e5-84f6-7f7f23e915e8.PNG)

**Comment by mmafe** [comment]
Issue resolved on development sites. If all looks good on the dev sites, I'll push to the master branch.

**Comment by jpinsent** [comment]
Looks good. Tested on AODA Demo and CCS dev site. 

![focus fixed](https://cloud.githubusercontent.com/assets/12450480/10291731/5d5c37d4-6b79-11e5-92d2-1b6c75028cd2.PNG)
