### ISSUE TITLE
G0 - Too many items in menu

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#28]
When there are too many items in the menu, the "My account" and "logout" buttons get pushed down onto the content. You can then not press the "edit" or "view" buttons when on a basic page, but only for top level pages in the menu (eg. "About CCS"). Also the top level of the breadcrumbs don't work either in this case.

**Comment by jpinsent** [comment]
A new menu bar has been implemented that wraps to another line when the menu fills up. This issue has been resolved
