### ISSUE TITLE
BR1 - Banner Link Text does not wrap when using a small screen size

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#29]
As you shrink the page, the link text for the banner slides under the buttons instead of wrapping around for responsiveness.

**Comment by brharp** [comment]
The link text was styled as a button, which does not wrap. Since adding the summary text below the link, we have removed the button style from the title text (it's now a plain link). This should fix the text wrapping issue.

**Comment by jszasz** [comment]
Responsiveness works now.
