### ISSUE TITLE
G1 - Breadcrumb text switches between title text and menu link text

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#31]
Which text is suppose to show in the breadcrumb? The nodes' title or menu text?

https://aoda.web.uoguelph.ca/aodademo/breadcrumb-test-6

Check out this page, there is a really long breadcrumb (Breadcrumb test 2 because i wanted.....menu) that is Menu Text. If you click on that breadcrumb, you go to the page and then the breadcrumb is the title text instead (Breadcrumb test 2 because title)

This also looks weird when the menu block is on the page as the breadcrumb shows the title of the page and the menu block shows the menu text.

**Comment by mmafe** [comment]
Title of the Node.

If we use menu text, we could run into issues if multiple menu items are referencing the same node.

**Comment by jszasz** [comment]
Ok, there is an issue then where a breabcrumb is showing the menu text, and then when you go to the page it is showing the title text. Refer to that link again, "Breadcrumb test 2 menu text" shows up in the breadcrumb, but when you click on it, "Breadcrumb test 2 title text" shows up.

**Comment by brharp** [comment]
Likely a moot point, because the page title has been removed from the breadcrumb (per the breadcrumb feature spec).

**Comment by mmafe** [comment]
Good point. :)

I guess the question could still relate to the parent breadcrumbs. For those we'll continue with the menu text that it's already showing.

**Comment by jszasz** [comment]
Issue Closed, current breadcrumbs only show menu text, and does not show current node so issue resolved.
