### ISSUE TITLE
G0 - "browse server" button is missing for adding featured image and attachments

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#32]
In the CkEditor you can add an image by browsing the server, where as when you are adding a featured image or an attachment, the file has to be on your computer to add it.

It would be good if both options were available side by side, so you could browse the server or just upload from your computer.

**Comment by brharp** [comment]
Drupal manages images and files attached to nodes (via fields) very differently than images uploaded via ckeditor. There is no way in Drupal to browse the server for file/image attachments.
