### ISSUE TITLE
G0 - authoring information cant be coppied if user doesn't exist in new site

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#33]
Trying to create this news article: https://aoda.web.uoguelph.ca/ccs/node/448

Setting the author to "mbfollin" (the original author) gives the following error "The username mbfollin does not exist." and will not let you publish the news article with that username.

**Comment by jszasz** [comment]
We will write them as anonymous for now, and if it matters, update it later on.

**Comment by brharp** [comment]
This is the intended behaviour for Drupal.
