### ISSUE TITLE
SR0 - "Who is eligible to use this service" details

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#42]
![who is eligible](https://cloud.githubusercontent.com/assets/12450523/8138038/a3b675d2-1115-11e5-8cc1-03359ddcb0dd.PNG)

Attached is a picture from the uoguelph.ca/ccs site. Under "Who is eligible to use this service" there is a details field to put details about who is eligible. That field is missing on the new content type.

**Comment by mmafe** [comment]
Looks like this is solved. We're using the Service Public Headings for the "Who is eligible to use this service" details section.

![who-details](https://cloud.githubusercontent.com/assets/1927902/9879658/5fa792e2-5b96-11e5-9045-a9831f67a96d.png)
