### ISSUE TITLE
P0 - Functional Author Testing - Can't manually add an inline image

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#44]
From Trello card...
Functional Tester: Confirm Author can...
-Manually add an inline image to the Body field of the Basic page

As an author roll, when I make a page and click on the image icon in CKEditor, I get shown the Image Properties screen. After clicking "browse server" to upload an image, the screen that comes up is a 403 - Forbidden.

**Comment by brharp** [comment]
IMCE must be configured per site, I have fixed this on the AODA demo site. Please try again.

**Comment by jszasz** [comment]
Fixed.
