### ISSUE TITLE
BR1 - When only 1 image is published, image does not show. [Chrome/Safari Only - works in FF]

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#48]
![image](https://cloud.githubusercontent.com/assets/1927902/8232481/2dff64ec-159e-11e5-9f33-b1997959724b.png)

When only 1 image is published, image does not show in Chrome or Safari. Image shows in Firefox.

**Comment by jszasz** [comment]
This bug currently affects the UAIC website, as they only have one banner. It is very obvious to a user that something is broken.

**Comment by mmafe** [comment]
This was fixed as part of hotfix_20150807_3.0.

Checked on AODADemo in Chrome and it appears to show with one slide.
