### ISSUE TITLE
N0 - Author can't make news articles sticky

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#61]
From Spec:

"Flag News Article to Appear at Top of List (Sticky): News Author has option to flag article so it appears at the top of the news listing page N1 – Listing Page for Multiple News Articles"

News Author does not have access to that menu.

**Comment by mmafe** [comment]
Updated spec so the editor has this ability (as opposed to the author). I think this'll help us avoid the scenario where everyone flags their article to appear at the top. Instead, fewer people (editors) will be in charge of determining the overall priority of articles.
