### ISSUE TITLE
N2 - Related Website Link does not display

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#63]
EG: https://aoda.web.uoguelph.ca/aodademo/test-external-url-link

Related website link is not showing anywhere on the view

**Comment by brharp** [comment]
The related website link is not part of the view, so I think this is an issue with the specification.

**Comment by mmafe** [comment]
Brent's right - Related website link is not part of the view.

The reason the field existed in the News content type is because of a now-deprecated requirement that allowed author/editors to link a news item in the N1 news listing directly to an external URL.
