### ISSUE TITLE
N1- on news listing view move title and text to left on news items that have no images

### ISSUE THREAD

**Issue by anncesar** [brharp/hjckrrh#65]
Looking at the listing view of OAC news on the new site- dev
https://dev.web.uoguelph.ca/oac/news
Many of OAC's news items are linked to external sources and don't have images. The view looks empty. We can either create an alternate view that shows no images, or expand the title and text in the view to fill up the white space on left. We think the latter is the better decision at this point.

**Comment by Dmelady** [comment]
Verified with Ann- has been resolved
