### ISSUE TITLE
P1- page layout issue- may be for all layouts (news, etc.)

### ISSUE THREAD

**Issue by anncesar** [brharp/hjckrrh#67]
If content is put into the top section (full width) of the page layout and not the 2 column section- it doesn't align with the banner/logo at top of page and 'bleeds' too far left.  see: aoda
https://aoda.web.uoguelph.ca/aodademo/ibidem-plaga-premo

**Comment by brharp** [comment]
When creating a panel with a Bootstrap layout, you must specify the column width of every region. For full width, set the region width to 12 columns.
