### ISSUE TITLE
E5 (Browse Events by Date) - update date formatting to remove comma

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#93]
Update Browse Events by Date to remove comma from the date-format. (i.e. January 2014 instead of January, 2014)

Change contextual date format to full month name (F) and full year (Y).

**Comment by mmafe** [comment]
Fixed as part of hotfix_20150807.3.0

**Comment by jpinsent** [comment]
This issue is confirmed fixed

![events view fix](https://cloud.githubusercontent.com/assets/12450480/9274825/dc6b78e6-4266-11e5-8735-5640d1fc4247.PNG)
