### ISSUE TITLE
F3 - Browse FAQ by Category lists all keywords

### ISSUE THREAD

**Issue by jpinsent** [brharp/hjckrrh#95]
Keywords are listed under "Browse FAQ by Category" instead of actual FAQ categories. They all link to 404 pages.
https://aoda.web.uoguelph.ca/aodademo/faq
![capture](https://cloud.githubusercontent.com/assets/12450480/8602909/ef7aa834-2642-11e5-8d5b-dd1ba3ab1344.PNG)

**Comment by brharp** [comment]
Fixed.
