### ISSUE TITLE
E2 - Heading for the main body of the event

### ISSUE THREAD

**Issue by jszasz** [brharp/hjckrrh#98]
eg. https://aoda.web.uoguelph.ca/oac/event/challenges-and-opportunities-investigating-economics-climate-change-great-lakes-perennial

The main body looks as if it is part of "Location", and the "Abstract" heading makes it seem like the rest isn't.

If there was a heading called...

Event Details
About this Event
Summary
Descritpion
etc.

...with the rest of the body underneath that, it would make it easier to separate the content both visually and with a screen reader. Plus it would be easier to make "Abstract" a H3 with a "Event Details" H2 above it.

**Comment by brharp** [comment]
Added "Details" header to event detail view.
